#!/bin/bash

READLINK=readlink

### find out the platform first
platform='Unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='macOS'
   READLINK=greadlink
fi

if ! [ -e `which $READLINK` ]
then
   echo "Can't find readlink or greadlink program, please make sure to have it installed"
   exit -1
fi

if [ "$1" = "commit" ] || [ "$1" = "ci" ]
then

files=""

tmpfile=.svnfiles
tmpmodified=.modified
tmpmodified_t=.modified_t

path=`$READLINK -f .`

while [ "$path" != "/" ] && [ "$path"x != "x" ]
do
ignorefile=$path/.svnignore
if [ -e "$ignorefile" ]
then
  break
else
  ignorefile=""
fi

path=`dirname $path`

done

/usr/bin/svn status | grep "^[M|A]" > $tmpmodified

if ! [ -z "$ignorefile" ] 
then
  cat $ignorefile | while read line
  do
    ### TODO with regex   
    grep -v $line $tmpmodified | tee $tmpmodified_t 
    #exit
    cp $tmpmodified_t $tmpfile
    cp $tmpmodified $tmpmodified_t
    cp $tmpfile $tmpmodified
  done   
fi

rm -f $tmpfile

#/usr/bin/svn status | grep -v module.mk | grep -v Makefile | grep "^[M|A]" | while read line
cat $tmpmodified | while read line
do
file=`echo $line | cut -f 2 -d " "`
echo found modified file $file
#files=$file" "$files

echo $file >> $tmpfile
done

if [ -e "$tmpfile" ]
then
files=`cat $tmpfile`

echo here are the files 
echo $files

#rm -f $tmpfile
#rm -f $tmpmodified
#rm -f $tmpmodified_t

if [ "$2" = "-m" ]
then
echo "checking in ..."
/usr/bin/svn "$@" $files
fi

else

echo "Nothing to do, there are no modifications"
fi

else
/usr/bin/svn "$@"
fi

