#!/bin/bash

if [ "$1" = "commit" ] || [ "$1" = "ci" ]
then

files=""

tmpfile=.svnfiles
tmpmodified=.modified
tmpmodified_t=.modified_t

path=`readlink -f .`

while [ "$path" != "/" ]
do
ignorefile=$path/.svnignore
if [ -e "$ignorefile" ]
then
  break
else
  ignorefile=""
fi

path=`dirname $path`

done

/usr/bin/svn status | grep "^[M|A]" > $tmpmodified

if ! [ -z "$ignorefile" ] 
then
  cat $ignorefile | while read line
  do
    ### TODO with regex   
    grep -v $line $tmpmodified | tee $tmpmodified_t 
    #exit
    cp $tmpmodified_t $tmpfile
    cp $tmpmodified $tmpmodified_t
    cp $tmpfile $tmpmodified
  done   
fi

rm -f $tmpfile

#/usr/bin/svn status | grep -v module.mk | grep -v Makefile | grep "^[M|A]" | while read line
cat $tmpmodified | while read line
do
file=`echo $line | cut -f 2 -d " "`
echo found modified file $file
#files=$file" "$files

echo $file >> $tmpfile
done

if [ -e "$tmpfile" ]
then
files=`cat $tmpfile`

echo here are the files 
echo $files

#rm -f $tmpfile
#rm -f $tmpmodified
#rm -f $tmpmodified_t

if [ "$2" = "-m" ]
then
echo "checking in ..."
/usr/bin/svn ci $files "$@"
fi

else

echo "Nothing to do, there are no modifications"
fi

else
/usr/bin/svn "$@"
fi

